### ISSUE TITLE
Floating WhatsApp-Help-desk button with opening-hours-widget

### ISSUE THREAD

**Issue by elwinschmitz** [rodekruis/helpful-information#116]
As a "user"  
I want to see the WhatsApp/Help-desk button prominently with opening-hours, 
So that I see whether the help-desk would be available right now.

![image](https://user-images.githubusercontent.com/1009183/152378083-fb626e8a-4561-4855-8d70-5086c418a8e8.png)

See also: https://www.figma.com/file/aK5YxTteydm08nKWWIeWMy/510-HIA?node-id=912%3A6314

## Details
- When de data (`WhatsAppNumber`, `HelpDeskOpeningHours`) is available, the button should be visible 'collapsed' by default.
- The icon should change from "left-pointing" to "right-pointing"
- The text-label + opening-hours should be clickable to open the WhatsApp-link (in a new window)
- The WhatsApp-link should be of the format: `https://wa.me/31600000000`
- (optonal?) When clicking/tapping 'outside' the widget, it should 'collapse'/go off-screen

## To Do
- [ ] Create a new `FloatingHelpDeskButton`-component
- [ ] Prepare/get data of opening-hours
- [ ] Add toggle logic
- [ ] (?) Add animations

**Comment by JLijftogt** [comment]
WhatsApp button also needed on the landing page

**Comment by elwinschmitz** [comment]
> WhatsApp button also needed on the landing page

It is possible to include the WhatsApp(or Telegram, or phone) contact-option as a configurable thing on the 'instance level'.

Changing the number or 'turning the button on/off' will require a code-change, instead of only a change in the sheet.

We could also get to the situation where the landing-page-button has a different number from the region-page-button... But that is just something to keep in mind I think...

@JLijftogt I also wonder; Is this design (with the interactive-sliding-widget-thing) still relevant?
Or would a 'simpler' shape also work, for example:
![image](https://user-images.githubusercontent.com/1009183/222400734-fd343c91-830e-49da-99b5-b6f2e11c8adf.png)

So it would be a (not too high) fixed positioned footer?
This would save some hassle/complexity in building a 'togglable' widget (of which the functionality could be missed by visitors, so they would never see the opening hours etc..)...
