### ISSUE TITLE
Translate headers (e.g. website, e-mail, phone number) into different language(s)

### ISSUE THREAD

**Issue by JLijftogt** [rodekruis/helpful-information#158]
Part of #151

**Comment by elwinschmitz** [comment]
## To Do

- [ ] Add `#KEY`-strings to 1st column
- [ ] Add transposed-column-mapping logic to find text-labels
- [ ] Replace row-indexes with `#KEY`-indexes
- [ ] Add new fields in sheet(s) + Examples + English:
  - [ ] Website
  - [ ] E-mail
  - [ ] Phone
  - [ ] Address
  - [ ] ? What do you need to know?
  - [ ] ? Opening hours
  - [ ] ? Basic Rights
- [ ] Decide on refactoring |?|-columns into "1 generic above details", "2 generic below details", "3 additional below details"

**Comment by elwinschmitz** [comment]
## Deployment / Production task-list
- [ ] In "Offers"-sheet: Remove `#FOR`-column
- [ ] Set "Referral Page"-sheet column-headers to: `#KEY`, `#VALUE`, `#EXAMPLE value`
- [ ] Set all "Referral Page"-sheet first column contents to  `#KEY`-column contents
- [ ] Add all `#offer.*` rows (with `#VALUE` and `#EXAMPLE`-cells)
