### ISSUE TITLE
Explore working with offer ID's

### ISSUE THREAD

**Issue by JLijftogt** [rodekruis/helpful-information#200]
As PO
I want to improve the way we work with offer ID's
So that it easier to add new offers with a unique offer ID and keeping the sequencing in tact and so that a link shared through the WhatsApp Helpdesk doesn't change when an offer ID is altered. 

Input Carry: 
Whenever districts add new offers in the excel file, the offer id of the offers that are already in the file changes. This offer ID is in the link, therefore it can be that for example a link that first brought you to information about Wereldhuis wil then later bring you to information about winter shelter. This is not very handy because districts send specific links to organisations that they can use. I don't know if this is clear, I can explain it to you during our call. And maybe you were already aware of this..:)

**Comment by elwinschmitz** [comment]
WIP:
- Add feature-flag: `useUrlSlugs`
- deploy step-by-step: dev → demo → staging UKR → staging → production UKR → production 
- Add demo-content to staging sheets as instructions?
- Add initial slugs by hand? Semi-automated via Sheet-formula?
- Add data-validation to column?
  - Also to Q&As? + fix existing data.
- start with only Offers? Or also (sub-)categories in 1 big sweep?
- add upgrade-redirects for old URL-format. (How?)

**Comment by elwinschmitz** [comment]
New URL-format:

- `/``$region``/``$category-slug``/``$sub-category-slug``/``$offer-slug``/`

?
