### ISSUE TITLE
Metrics: Being able to look back for longer than 30 days

### ISSUE THREAD

**Issue by JLijftogt** [rodekruis/helpful-information#378]
**As:** 
HIA coordinator at HQ

**I want to:**
Be able to see the user metrics of more than 30 days ago

**So that I:**
Always have insights into relevant user metrics, and can answer specific questions.

Example: the other day (in August) I wanted to go back and check something in June, but that is currently not possible in the dashboard.

**Comment by elwinschmitz** [comment]
Maybe using Workbooks;
See https://learn.microsoft.com/en-us/azure/azure-monitor/visualize/workbooks-limits
