### ISSUE TITLE
Metrics: # unique users

### ISSUE THREAD

**Issue by JLijftogt** [rodekruis/helpful-information#379]
**As:** 
HIA coordinator at HQ

**I want to:** 
Easily see the total number of unique users in a month

**So that I:** 
Don't have to manually add up the unique users per day to come to the total, and so that I'm ultimately faster with creating the monthly update

**Comment by elwinschmitz** [comment]
See definitions of "session" or "user": https://learn.microsoft.com/en-us/azure/azure-monitor/app/javascript#configuration
