### ISSUE TITLE
Metrics: can we link the distinction between device type to duration of visit

### ISSUE THREAD

**Issue by JLijftogt** [rodekruis/helpful-information#384]
**As:** 
HIA coordinator at HQ

**I want to:** 
Know what the average duration of a HIA visit is, without the average being higher because Aid Workers (i.e. active on the Helpdesk) have it open in a tab for a long time

**So that I:** 
Can say more about the relevance and usefulness of the information that is on HIA

**Comment by elwinschmitz** [comment]
See https://learn.microsoft.com/en-us/azure/azure-monitor/app/javascript?tabs=snippet#enable-time-on-page-tracking
