### ISSUE TITLE
Remove Covid19 vaccinations button from HIA UM landing page

### ISSUE THREAD

**Issue by JLijftogt** [rodekruis/helpful-information#623]
As Project Coordinator
I want to remove the Covid19 vaccinations button from the landing page
Because it's not as relevant anymore and because the same information is still accessible through the Covid category that is part of each district

**Comment by elwinschmitz** [comment]
@JLijftogt Does this also apply to all the different covid-specific Offer-fields?

It would really 'clean things up' if we removed all those as well.

**Comment by JLijftogt** [comment]
@elwinschmitz The whole sheet for Covid19 vaccinations can be removed (I'd like to save it on Teams though, so we can still access it and its structure if ever needed again). It should stay as a category (i.e. as part of Utrecht) and sub-category (i.e. as part of Amsterdam) in all cities.
