### ISSUE TITLE
Prepare user-tests' data/previews

### ISSUE THREAD

**Issue by elwinschmitz** [rodekruis/helpful-information#690]

**Comment by JLijftogt** [comment]
Based on our discussion with Carry:  

- Replacing/updating all current staging sheets with the production sheets -> I think we can just copy/paste the sheet content right? (this so we have the latest version of the content for each city in staging for the user tests)
- Applying the new translation feature to all staging sheets
- Giving half of the staging sheets the different color scheme: navy buttons and white icons

- Carry herself will work on the content in relation to legal & basic rights that she wants to test

**Comment by JLijftogt** [comment]
Relevant staging sheets: Amsterdam, the Hague, Almere
