### ISSUE TITLE
Results of User Tests 2023-06

### ISSUE THREAD

**Issue by elwinschmitz** [rodekruis/helpful-information#763]
Following HIA-insights-2023.pptx

- [x] 1. Language selector to be designed and implemented according to the feedback. → rodekruis/helpful-information#638
- [ ] 2. Check the quality of the translation
- [x] #764
- [x] 4. Navigation/directions – solution to be investigated further (maybe categorize per region)
  - [x] #777 
- [x] 5. Accessibility:
  - [x] #765
  - [x] #766
- [x] 6. Further research to be done by the design team related to improving the affordance of the buttons & solution to be defined and implemented

**Comment by JLijftogt** [comment]
1. Anca and Elwin working together
2. Anca and Jonath working together
3. Anca and Elwin working together
4. Elwin and Jonath working together, then involving Anca
5. Anca and Elwin working together
6. Anca in the lead

Decision: working in sprint cycles of 2 weeks

**Comment by JLijftogt** [comment]
Input Carry/Tracey:

Additional UT insights: 
- More visible that HIA is from the Red Cross. 

From previous UT insights: 
- What can the Red Cross do for me?
- Journey for someone who is new in/arrives for the first time in Amsterdam

Possibility to highlight two buttons: 
- What can the Red Cross do for me? 
- What to do/where to go first? (linked to primary target group)
