### ISSUE TITLE
Find a way to secure certain FAQ's

### ISSUE THREAD

**Issue by JLijftogt** [rodekruis/helpful-information#843]
As a... HIA & Helpdesk coordinator at HQ
I want to... be able to add information to the HIA FAQ instance that is not publicly available but instead only accessible by staff and volunteers (for example by providing a password)
So that I... can use the HIA FAQ as the one central point of information, including descriptions of internal processes around i.e. voucher support, organograms etc. 

Context: 
The (WhatsApp) helpdesk for undocumented migrants, for refugees from Ukraine and for potential other target groups is going to merge to one helpdesk in October. This also means the team will start to operate as one big team. This team wants to use the HIA FAQ as the one central point of information for the helpdesk agents to access when answering questions. This means that there will be different/new information types on the HIA FAQ.

**Comment by elwinschmitz** [comment]
- [x] Create prototype to use 'local' data
- [x] Create prototype to fetch private Google Sheet in GitHub Actions workflow
- [x] Create new instance with static (non-google) build
- [x] Add Login (config + buttons) - GitHub-login as test
- [x] Secure private data to relevant users only
- [x] Allow login for `@redcross.nl`-accounts (Depends on OGD)
- [x] Find a way to limit users (invite-only as `aidworker`-users)
- [x] Find a way to "trigger" a build -> Using comment-on-GitHub-issue
- [ ] Demo

**Comment by elwinschmitz** [comment]
Preview: https://to.510.global/hia-faq-private 

- Currently anyone with a Microsoft- or GitHub-account can use the "login"-link to "signup" for our app, but these users won't have access to anything special.
- We(=I) can manually invite specific @redcross.nl addresses who then can access everything that is in the "Private FAQ"-sheet/link

- A separate Google Sheet is created to contain the 'internal/private' content
- Multiple private google sheets can be added to the same instance;
  - They all need to be private; As there is no more 'connection' between the HIA-website and the Google Sheets API
  - A special "service account"-user needs to be invited tot "view" the sheet, for it all to work.
 
- Whenever there are changes to any of the Google Sheets the whole instance/website needs to be 'published'.
  - This can be done through a GitHub-issue: #880
  - We can add (up to 10) users that will be allowed to trigger an update.  
    These users only have to "post a comment" on that issue to trigger the update
  - We could also set-up a schedule to trigger it automatically "once a day" or similar (depends on the rate/speed of changes)
